### ISSUE TITLE
ECS Uni Bonn: Doppelte ECS-Referenzen nach Update am ILIAS-Kurs [ask][low]

### ISSUE THREAD

**Issue by ckozianka** [freeit/CampusConnect#1]
Hallo Herr Bernlöhr,
wir betreiben an der Uni Bonn einen ECS-Server, der die ILIAS-Installationen von Köln und Bonn verbindet. Hier haben wir seit einiger Zeit folgendes Problem:
- Nach Ablauf eines Semesters werden die ECS-Referenzen in eine Kategorie unterhalb der Kategorie mit der Import-ID verschoben.
- Sobald an den Kursen des abgelaufenen Semesters, die für den ECS freigegeben wurden, eine Änderung in den Kurseinstellungen vorgenommen wird (z.B. den Kurstitel ändern), wird erneut eine Referenz in der Wurzelkategorie mit der Import-ID angelegt. Wir haben dann zwei Referenzen auf den selben freigegebenen Kurs, einmal in der Kategorie mit der Import-ID und einmal in der Kategorie, in die die Kurse des vergangenen Semesters verschoben wurden.
- Das hat zur Folge, dass mit jeder Änderung an alten Kursen, diese wieder in der Kategorie für das aktuelle Semester auftauchen. Da wir nach Ablauf eines Semesters allen ILIAS-Kursen ein Semesterkürzel im Titel hinzufügen, tauchen diese plötzlich wieder im aktuellen Semester auf und müssen manuell gelöscht werden.

Gibt es eine Möglichkeit, dies zu verhindern?

Hier meine Kontaktdaten:
Carsten Kozianka
Rheinische Friedrich-Wilhelms-Universität Bonn
eCampus eLearning-Services
E-Mail: kozianka@uni-bonn.de
Telefon: +49 228 73 4544

Herzliche Grüße
carsten Kozianka

**Comment by freeit** [comment]
Hallo Herr Kozianka,

Änderungen an alten Kursen, die nach Ablauf eines Semesters in eine andere Kategorie verschoben wurden, legt ILIAS in der Tat momentan wieder als neuen Kurslink unter der Wurzelkategorie (Import-ID) an. Ob, wann und wo ILIAS Kurslinks erstmalig oder nach einem Update anlegt, liegt jedoch unter voller Kontrolle von ILIAS (ECS Konnektor Implementierung) und kann bzw. soll auch nicht durch den ECS geregelt werden. Hier wäre es in der Tat sinnvoll bzw. notwendig, daß ILIAS vor Anlegen eines Kurslinks prüft, ob dieser schon bereits anderstwo existiert (verschoben in eine andere Katergorie) und es dementsprechend   unterläßt, unter Wurzelkategorie diesen erneut anzulegen.

Ich schlage vor, dieses Verhalten von ILIAS mit Stefan Meyer (Leifos) zu besprechen und seine Meinung bzgl. einer Änderung/Anpassung von ILIAS einzuholen.

Gruß
Heiko Bernlöhr

**Comment by ckozianka** [comment]
Hallo Herr Bernlöhr,
herzlichen Dank für die schnelle Rückmeldung und Ihre Hilfe.
Schöne Grüße
Carsten Kozianka
